---
title: "t1d_pred_figures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(cowplot)
library(stringr)
library(reshape2)
```

```{r}
#plot of modeling results overview
setwd('~/Dropbox (HMS)/RagGroup Team Folder/t1d_TEDDY_db/figures/')

results<-read.csv('supp_table1_for_figure_1.csv')
rownames(results)<-results$X

results<-melt(results)

results_data<-results[1:16,]
results_errors<-results[17:32,]

results<-cbind(results_data,results_errors[,3])
colnames(results)<-c('Model','Data Type','Accuracy','Error')

ggplot(results, aes(x=as.factor(Model), y=Accuracy, fill=`Data Type`)) +geom_bar(position=position_dodge(), stat="identity", colour='black') +geom_errorbar(aes(ymin=Accuracy-Error, ymax=Accuracy+Error), width=.2,position=position_dodge(.9))+theme(legend.title = element_blank()) + theme(axis.text.x = element_text(angle = 45, hjust =1))+ggtitle('Prediction Accuracy by Data Type and Model')+xlab('')

ggsave('~/Dropbox (HMS)/RagGroup Team Folder/t1d_TEDDY_db/figures/prediction_overview_by_data_type.pdf',height=6,width=6,units = 'in')

#axis labels from this plot need to be adjusted in illustrator

```


```{r}
setwd('~/Dropbox (HMS)/RagGroup Team Folder/t1d_TEDDY_db/')

plot_cag_count_files<-function(filename){
  d=read.csv(filename,sep='\t')
  d$Percentage=round(d$X0/sum(d$X0),3)*100
  tgc=sum(d$X0)
  d=d[order(d$X0,decreasing = T),][1:10,]
  d=d[complete.cases(d), ]
  d$X <- factor(d$X, levels = d$X)
  colnames(d)[1]='Taxonomic Annotation'
  cagname=str_remove(filename, "_taxa_mapping_counts.tsv")
  ggplot(d,aes(x=d$`Taxonomic Annotation`,y=Percentage))+geom_bar(stat = 'identity')+ggtitle(paste(cagname,' top taxonomic annotations (total gene count = ',tgc,')',sep=''))+ theme(axis.text.x = element_text(angle = 45, hjust =1,size=10))+xlab('')
  ggsave(paste("figures/",cagname,"_gene_annotation_plot.pdf",sep=''),height=6,width=6,units='in')
  }

dirFiles<-list.files()
countFiles<-dirFiles[grep("counts.tsv", dirFiles)]

for(file in countFiles){
  plot_cag_count_files(file)
}




```